- labels:
    project: SMC
    env: prod
    source: blackbox
    monitoring-scope: internal
    service: SMC App
    component: SMC App
    enable_alert_latency: "true"
    enable_alert_status_code: "true"
    enable_alert_down: "true"
    alert_level_critical: mention,discord
    alert_level_info: discord
    alert_level_warning: discord
    discord_channel: '#smc-alert'
    manager: "Destrier"
  targets:
    - "https://showmeyourcode.online"

- labels:
    project: SMC
    env: prod
    source: blackbox
    monitoring-scope: internal
    service: Temporal
    component: Temporal
    enable_alert_latency: "true"
    enable_alert_status_code: "true"
    enable_alert_down: "true"
    alert_level_critical: mention,discord
    alert_level_info: discord
    alert_level_warning: discord
    discord_channel: '#smc-alert'
    manager: "Destrier"
  targets:
    - "https://temporal.showmeyourcode.online"    

- labels:
    project: SMC
    env: prod
    source: blackbox
    monitoring-scope: internal
    service: Traefik
    component: Traefik
    enable_alert_latency: "true"
    enable_alert_status_code: "true"
    enable_alert_down: "true"
    alert_level_critical: mention,discord
    alert_level_info: discord
    alert_level_warning: discord
    discord_channel: '#smc-alert'
    manager: "Destrier"
  targets:
    - "https://traefik.showmeyourcode.online"

- labels:
    project: SMC
    env: prod
    source: blackbox
    monitoring-scope: internal
    service: Grafana
    component: Grafana
    enable_alert_latency: "true"
    enable_alert_status_code: "true"
    enable_alert_down: "true"
    alert_level_critical: mention,discord
    alert_level_info: discord
    alert_level_warning: discord
    discord_channel: '#smc-alert'
    manager: "Destrier"
  targets:
    - "https://grafana.showmeyourcode.online"

- labels:
    project: SMC
    env: prod
    source: blackbox
    monitoring-scope: internal
    service: minio
    component: minio
    enable_alert_latency: "true"
    enable_alert_status_code: "true"
    enable_alert_down: "true"
    alert_level_critical: mention,discord
    alert_level_info: discord
    alert_level_warning: discord
    discord_channel: '#smc-alert'
    manager: "Destrier"
  targets:
    - "https://minio.showmeyourcode.online"

- labels:
    project: SMC
    env: prod
    source: blackbox
    monitoring-scope: internal  
    service: Prometheus
    component: Prometheus
    enable_alert_latency: "true"
    enable_alert_status_code: "true"
    enable_alert_down: "true"
    alert_level_critical: mention,discord
    alert_level_info: discord
    alert_level_warning: discord
    discord_channel: '#smc-alert'
    manager: "Destrier"
  targets:
    - "https://prometheus.showmeyourcode.online"

- labels:
    project: SMC
    env: prod
    source: blackbox
    monitoring-scope: internal
    service: blackbox
    component: blackbox
    enable_alert_latency: "true"
    enable_alert_status_code: "true"
    enable_alert_down: "true"
    alert_level_critical: mention,discord
    alert_level_info: discord
    alert_level_warning: discord
    discord_channel: '#smc-alert'
    manager: "Destrier"
  targets:
    - "https://blackbox-exporter.showmeyourcode.online"

- labels:
    project: SMC
    env: prod
    source: blackbox
    monitoring-scope: internal
    service: Tempo
    component: Tempo
    enable_alert_latency: "true"
    enable_alert_status_code: "true"
    enable_alert_down: "true"
    alert_level_critical: mention,discord
    alert_level_info: discord
    alert_level_warning: discord
    discord_channel: '#smc-alert'
    manager: "Destrier"
  targets:
    - "https://tempo.showmeyourcode.online"

- labels:
    project: SMC
    env: prod
    source: blackbox
    monitoring-scope: internal
    service: Loki
    component: Loki
    enable_alert_latency: "true"
    enable_alert_status_code: "true"
    enable_alert_down: "true"
    alert_level_critical: mention,discord
    alert_level_info: discord
    alert_level_warning: discord
    discord_channel: '#smc-alert'
    manager: "Destrier"
  targets:
    - "https://loki.showmeyourcode.online"

- labels:
    project: SMC
    env: prod
    source: blackbox
    monitoring-scope: internal
    service: Alertmanager
    component: Alertmanager
    enable_alert_latency: "true"
    enable_alert_status_code: "true"
    enable_alert_down: "true"
    alert_level_critical: mention,discord
    alert_level_info: discord
    alert_level_warning: discord
    discord_channel: '#smc-alert'
    manager: "Destrier"
  targets:
    - "https://alertmanager.showmeyourcode.online"

#- labels:
#    project: SMC
#    env: prod
#    source: blackbox
#    monitoring-scope: internal
#    service: infisical
#    component: infisical
#    enable_alert_latency: "true"
#    enable_alert_status_code: "true"
#    enable_alert_down: "true"
#    alert_level_critical: mention,discord
#    alert_level_info: discord
#    alert_level_warning: discord
#    discord_channel: '#smc-alert'
#    manager: "Destrier"
#  targets:
#    - "https://infisical.showmeyourcode.online"

#- labels:
#    project: SMC
#    env: prod
#    source: blackbox
#    monitoring-scope: internal
#    service: bitwarden
#    component: bitwarden
#    enable_alert_latency: "true"
#    enable_alert_status_code: "true"
#    enable_alert_down: "true"
#    alert_level_critical: mention,discord
#    alert_level_info: discord
#    alert_level_warning: discord
#    discord_channel: '#smc-alert'
#    manager: "Destrier"
#  targets:
#    - "https://bitwarden.showmeyourcode.online"

#- labels:
#    project: SMC
#    env: prod
#    source: blackbox
#    monitoring-scope: internal
#    service: netbox
#    component: netbox
#    enable_alert_latency: "true"
#    enable_alert_status_code: "true"
#    enable_alert_down: "true"
#    alert_level_critical: mention,discord
#    alert_level_info: discord
#    alert_level_warning: discord
#    discord_channel: '#smc-alert'
#    manager: "Destrier"
#  targets:
#    - "https://netbox.showmeyourcode.online"